### PR TITLE
Fix native system headers directory in config.gcc

### PR DESCRIPTION
**Pull request by Blackhex**
The fix as suggested at https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/issues/17.

PR verified by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/9383070027.

### CODE REVIEW

**Review by eukarpov — COMMENTED** [review]
I am not sure it is right way to use sys-root for mingw.

**Comment by Blackhex** [comment]
JFYI, MSYS2 uses this patch https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0005-Windows-Don-t-ignore-native-system-header-dir.patch on top of the proposed solution.

**Comment by eukarpov** [comment]
> JFYI, MSYS2 uses this patch https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0005-Windows-Don-t-ignore-native-system-header-dir.patch on top of the proposed solution.

Yes, it could be another option for the workaround.

**Comment by eukarpov** [comment]
I think this PR is not needed anymore.

**Comment by Blackhex** [comment]
Yes, it's part of MSYS2 recipes.

**Pull request closed without merging**
